info:
  version: 0.0.1

spring:
  application:
    name: hexagonal

  jpa:
    hibernate:
      ddl-auto: create

  jackson:
    serialization:
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
  date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat

application:
